name = "glua"
target = "erlang"
version = "1.0.0"

description = "A library for embedding Lua in Gleam applications"
licences = ["Apache-2.0"]
repository = { type = "github", user = "selenil", repo = "glua" }

[documentation]
pages = [
    { title = "Changelog", path = "changelog.html", source = "./CHANGELOG.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
luerl = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
